CREATE DATABASE IF NOT EXISTS Password_Manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE Password_Manager;

CREATE TABLE IF NOT EXISTS vault_metadata (
  id INT PRIMARY KEY AUTO_INCREMENT,
  kdf_salt VARBINARY(64) NOT NULL,
  kdf_params TEXT NOT NULL,
  master_hash VARBINARY(128) NOT NULL,
  enc_version INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  website VARCHAR(255) NOT NULL,
  password_encrypted LONGBLOB NOT NULL,
  iv VARBINARY(64) NOT NULL,
  enc_version INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_website (website)
);
